### PR TITLE
Added 2 small helpers for Fluid Tanks

### PR DESCRIPTION
**Pull request by Rundas01**
## What
Fluid Tanks don't have methods to return how much space they have. I needed that for some primitive multiblocks and thought that other people might need the same at some point. If deemed unnecessary, you can yeet this PR.

### CODE REVIEW

**Comment by Pumpkin7266** [comment]
btw can you check dev-talks on discord?

**Review by screret — COMMENTED** [review]
make it a helper method instead tyvm

**Comment by screret** [comment]
in like, GTTransferUtils

**Comment by krossgg** [comment]
Why is this necessary? You can use the `fill` method with the `simulate` flag in order to test if a tank can take the fluid you're trying to put in.

**Comment by Rundas01** [comment]
> Why is this necessary? You can use the `fill` method with the `simulate` flag in order to test if a tank can take the fluid you're trying to put in.

didn't know you can do that. like I said, if unnecessary, yeet the PR

**Pull request closed without merging**
