### PR TITLE
Solar Panels

### PR DESCRIPTION
**Pull request by poggers16**
solar panels.
dont ask why i have 26 unrelated commits

### CODE REVIEW

**Comment by screret** [comment]
Hear me out: make a new branch based on the current 1.19/1.20 and copy all the relevant stuff into that

**Comment by poggers16** [comment]
i aint doing all of that :sob:

**Review by TheAlaskanPhysicist — APPROVED** [review]
LGTM so long as it runs lol

**Comment by poggers16** [comment]
great, now i have to do literally everything again, wish me luck ;D

**Comment by mikerooni** [comment]
> great, now i have to do literally everything again, wish me luck ;D

I've restored your branch in #559 - feel free to continue working from there

**Pull request closed without merging**
