### PR TITLE
Fix issue 1484.

### PR DESCRIPTION
**Pull request by liansishen**
Multiblock no need to check OverclockTier.

### CODE REVIEW

**Comment by liansishen** [comment]
Oh now multiblock can do recipe over the voltage.

**Comment by DancingSnow0517** [comment]
I am unable to reproduce this issue

**Comment by YoungOnionMC** [comment]
I jus thought of the same fix in [44b749a](https://github.com/GregTechCEu/GregTech-Modern/pull/1468/commits/44b749a688511ecd4196e193e945704dc8709f30)

**Comment by liansishen** [comment]
OK,I'll close the pr.

**Pull request closed without merging**
