### PR TITLE
Async Recipes Searching Task

### PR DESCRIPTION
**Pull request by Yefancy**
Using CompletableFuture for async tasks (thread pool from Util.backgroundExecutor).

Behavior:
1. Async searching recipes in `Util.backgroundExecutor`. 
2. schedule comple task (handle matches) in the thread of `MinecraftServer`.
3. if seaching error with eceptions (In theory, it shouldn't happen), try to search recipe again in main thread.
4. handle searched recipes in main thread as usual.

### CODE REVIEW

**Comment by Yefancy** [comment]
I hope someone who have a base of massive machines to help test it.

**Comment by Yefancy** [comment]
gtceu-forge-1.20.1-1.0.16.jar

**Comment by Yefancy** [comment]
[gtceu-forge-1.20.1-1.0.16.a.jar.zip](https://github.com/GregTechCEu/GregTech-Modern/files/13448402/gtceu-forge-1.20.1-1.0.16.a.jar.zip)

**Comment by loving2** [comment]
My server is crashing with a ticking block entity error with this build installed - [latest.log](https://mclo.gs/9nT5Hcx) and [crash report](https://mclo.gs/ExSLmdx)

The server does start up with 1.0.15.a in place. It claims to be a distillation tower that is ticking, and if it is the one I think it is, it should be distilling severely hydro cracked heavy fuel.

**Comment by Arborsm** [comment]
> My server is crashing with a ticking block entity error with this build installed - [latest.log](https://mclo.gs/9nT5Hcx) and [crash report](https://mclo.gs/ExSLmdx)
> 
> The server does start up with 1.0.15.a in place. It claims to be a distillation tower that is ticking, and if it is the one I think it is, it should be distilling severely hydro cracked heavy fuel.

out of date，try https://discord.com/channels/701354865217110096/1089296351906504835/1177298977020977222

**Comment by loving2** [comment]
Looks much better on that build! I'll update should I find any issues!

**Review by screret — APPROVED** [review]

**Pull request merged**
