### PR TITLE
Cherrypick stuff to 1.20

### PR DESCRIPTION
**Pull request by screret**

### CODE REVIEW

**Comment by mikerooni** [comment]
@screret do I need to review the first four commits as well or are those just exact cherrypicks as they are in 1.19?

**Comment by screret** [comment]
exact.

**Comment by mikerooni** [comment]
alright, I'll review just by the last commit then

**Comment by screret** [comment]
there's nothing to review tho

**Review by mikerooni — APPROVED** [review]
Reviewed 1b5ed7c94c16ddbdaa35a2b00b898eaf8f7bad1b only, as the others are exact cherrypicks.

**Pull request merged**
