### PR TITLE
fix #1326

### LINKED ISSUE #1326: Bedrock miner improvements
### Cross-mod Integration

KubeJS?

### Feature Description

When bedrock veins are edited and server is reloaded the server crashes, this should be redone to allow reloading/regenerating chunks without restarting, as well as maintain existing data properly or entirely regenerate the veins when data is changed

When this happens it also deletes ALL existing bedrock veins from a world and stops generation of new ones
This deleting effect is also caused when removing a mod, editing veins WITHOUT crashing, or removing nearly any data from a world

### PR DESCRIPTION
**Pull request by screret**
fixes #1326

### CODE REVIEW

**Review by mikerooni — APPROVED** [review]

**Comment by Deepacat** [comment]
[crash-2024-05-27_15.54.44-server.txt](https://github.com/GregTechCEu/GregTech-Modern/files/15461796/crash-2024-05-27_15.54.44-server.txt)
still crashed after a reload,
bedrock ore veins still vanishing from the world permanently if any are added

**Comment by Deepacat** [comment]
from testing the crash only happens occasionally after reloading edited veins, randomly or on world quit
most of the time veins can be edited and reloaded, with old veins persisting but no longer generating, and new veins generating fine in new chunks seemingly
unsure what causes the crashing and vanishing, will test more

**Comment by Deepacat** [comment]
I lied removed veins still generate

**Comment by Deepacat** [comment]
The more I test the more I am confused

**Comment by Deepacat** [comment]
Seems the crash is related to pausing while a prospector is rendering, specifically after a reload? not to bedrock vein changes within kubejs, testing more and will make an issue

**Pull request merged**
