### PR TITLE
Fix many recipes; etc

### LINKED ISSUE #262: Unable to add ore veins to Ad Astra's Moon
### GregTech CEu Version

1.0.9

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

The ore vein specified via KubeJS scripts should spawn on the moon and be immediately picked up by max-tier prospector.

### Actual Behavior

No custom ore veins spawn on the moon.

### Steps to Reproduce

1. Installed mods:

Gregtech Modern 1.0.9
KubeJS 1902.6.1-build.337
Ad Astra 1.12.7

2. Added the following script to startup scripts:

```
GTCEuStartupEvents.registry('gtceu:world_gen_layer', event => {
    event.create('moon')
        .target(['ad_astra:moon_stone', 'minecraft:soul_soil'])
})

GTCEuStartupEvents.registry('gtceu:tag_prefix', event => {
    event.create('moon', 'ore')
        .stateSupplier(() => Block.getBlock('ad_astra:moon_stone').defaultBlockState())
        .material(Material.STONE)
        .color(MaterialColor.STONE)
        .sound(SoundType.STONE)
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
})
```

3. Added following script to server scripts:

```
GTCEuServerEvents.oreVeins(event => {
    event.add("modpack:moon_manganese_vein", vein => {
        vein.clusterSize(40)
            .weight(200)
            .layer("moon")
            .density(0.7)
            .heightRange({
                height: {
                    type: "uniform",
                    min_inclusive: {
                      absolute: 60
                    },
                    max_inclusive: {
                      absolute: 256
                    }
                }
            })
            .discardChanceOnAirExposure(0)
            .addSpawnDimension("ad_astra:moon")
            .addSpawnBiome({"type": "forge:any"})
            .generator(vein.generatorBuilder("gtceu:layer")
                .withLayerPattern(() => GTLayerPattern.builder([['ad_astra:moon_stone', 'minecraft:soul_soil']])
                    .layer(l => l.weight(3).mat(GTMaterials.Grossular).size(2, 2))
                    .layer(l => l.weight(3).mat(GTMaterials.Pyrolusite).size(2, 2))
                    .layer(l => l.weight(1).mat(GTMaterials.Pyrochlore).size(1, 3))
                    .layer(l => l.weight(1).mat(GTMaterials.Tantalite).size(1, 3))
                    .build()))
    })
})
```

4. On startup, create new world, teleport to the moon via command: `/execute in ad_astra:moon run teleport @p ~ 120 ~`
5. Give self prospector, see that there are no custom ores on the moon.

### Additional Information

It's likely I'm missing something in my KubeJS script, but if we can figure it out, I can contribute what I've learned as documentation to the project :)

### LINKED ISSUE #264: Add recipes to raw ore blocks
### Cross-mod Integration

_No response_

### Feature Description

Add recipes to Gregtech raw ore blocks like vanilla ones do have.
Example of a vanilla raw ore block recipe:
Screenshot_20230803_161537

### LINKED ISSUE #268: Planks Recipes Aren't Nerfed When "nerfWoodCrafting" Is Enabled
### GregTech CEu Version

fabric-1.20.1-1.0.10

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

1 log -> 2 planks

### Actual Behavior

1 log -> 4 planks

### Steps to Reproduce

1. Enable "nerfWoodCrafting" in config.
1. Get a log or a wood.
1. Craft it into planks in crafting table.
1. Observe the count of the planks.

### Additional Information

#219

Loaded 74 mods:
- ae2 15.0.4-beta
- cardinal-components-base 5.2.1
- cardinal-components-entity 5.2.1
- cloth-config 11.0.99
- com_github_llamalad7_mixinextras 0.2.0-beta.6
- configuration 2.2.0
- editenchanting 1.1.2
- emi 1.0.18+1.20.1+fabric
- enchantinginfuser 8.0.1
- enchantist ${version}
- fabric-api 0.83.1+1.20.1
- fabric-api-base 0.4.29+b04edc7a77
- fabric-api-lookup-api-v1 1.6.34+4d8536c977
- fabric-biome-api-v1 13.0.10+b3afc78b77
- fabric-block-api-v1 1.0.9+e022e5d177
- fabric-blockrenderlayer-v1 1.1.39+b3afc78b77
- fabric-client-tags-api-v1 1.0.20+b3afc78b77
- fabric-command-api-v2 2.2.11+b3afc78b77
- fabric-content-registries-v0 4.0.7+b3afc78b77
- fabric-convention-tags-v1 1.5.3+b3afc78b77
- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
- fabric-data-generation-api-v1 12.1.11+b3afc78b77
- fabric-dimensions-v1 2.1.51+b3afc78b77
- fabric-entity-events-v1 1.5.21+b3afc78b77
- fabric-events-interaction-v0 0.6.0+b3afc78b77
- fabric-game-rule-api-v1 1.0.38+b04edc7a77
- fabric-gametest-api-v1 1.2.10+b3afc78b77
- fabric-item-api-v1 2.1.26+b3afc78b77
- fabric-item-group-api-v1 4.0.7+b3afc78b77
- fabric-key-binding-api-v1 1.0.36+fb8d95da77
- fabric-lifecycle-events-v1 2.2.20+b3afc78b77
- fabric-loot-api-v2 1.1.37+b3afc78b77
- fabric-message-api-v1 5.1.6+b3afc78b77
- fabric-mining-level-api-v1 2.1.47+b3afc78b77
- fabric-models-v0 0.3.35+b3afc78b77
- fabric-networking-api-v1 1.3.8+b3afc78b77
- fabric-object-builder-api-v1 11.0.6+b3afc78b77
- fabric-particles-v1 1.0.28+b3afc78b77
- fabric-recipe-api-v1 1.0.18+b3afc78b77
- fabric-registry-sync-v0 2.2.6+b3afc78b77
- fabric-renderer-api-v1 3.0.1+b3afc78b77
- fabric-renderer-indigo 1.3.1+b3afc78b77
- fabric-rendering-data-attachment-v1 0.3.33+b3afc78b77
- fabric-rendering-fluids-v1 3.0.26+b3afc78b77
- fabric-rendering-v1 3.0.6+b3afc78b77
- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
- fabric-resource-loader-v0 0.11.7+f7923f6d77
- fabric-screen-api-v1 2.0.6+b3afc78b77
- fabric-screen-handler-api-v1 1.3.27+b3afc78b77
- fabric-sound-api-v1 1.0.12+b3afc78b77
- fabric-transfer-api-v1 3.2.2+b3afc78b77
- fabric-transitive-access-wideners-v1 4.2.0+b3afc78b77
- fabricloader 0.14.21
- forgeconfigapiport 8.0.0
- gtceu 1.0.10
- iceberg 1.1.13
- jade 11.2.2
- java 17
- ldlib 1.0.16.b
- minecraft 1.20.1
- modmenu 7.1.0
- porting_lib_core 2.1.1021+1.20
- porting_lib_data 2.1.1021+1.20
- porting_lib_gametest 2.1.1021+1.20
- porting_lib_model_generators 2.1.1021+1.20
- porting_lib_model_materials 2.1.1021+1.20
- porting_lib_tags 3.0
- porting_lib_utility 2.1.1021+1.20
- puzzleslib 8.0.12
- registrate-fabric 1.3.59-MC1.20
- team_reborn_energy 2.3.0
- travelersbackpack 1.20.1-9.1.2
- universalenchants 8.0.0
  - extensibleenums 7.0.1

### LINKED ISSUE #274: Incorrect Acacia Fence Recipe
### GregTech CEu Version

fabric-1.20.1-1.0.10-build_132

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

shaped_fence
shaped_fence_gate
shaped_fence_gate_screws

### Actual Behavior

shaped_acacia_fence
shaped_acacia_fence_gate
shaped_acacia_fence_gate_screws

### Steps to Reproduce

1. Install JEI, REI or EMI.
2. Look up recipes of acacia fence and gate.

### Additional Information

Only acacia recipes are incorrect. Other wood types recipes are normal.

### LINKED ISSUE #286: Unknown Missing Ingredients in Recipes of Some Machines
### GregTech CEu Version

fabric-1.20.1-1.0.10-build_132

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

Craft it.

### Actual Behavior

REI shows that the ingredient is mising. I can't craft it in crafting table or AE2 crafting terminal, either.
image
image

### Steps to Reproduce

1. Check recipe of basic mixer and basic canner.
2. Check the missing ingredient.

### Additional Information

[latest.log](https://github.com/GregTechCEu/GregTech-Modern/files/12305045/latest.log)

### PR DESCRIPTION
**Pull request by screret**
fixes #286
fixes #274
fixes #268 
fixes #264

### CODE REVIEW

**Comment by Yefancy** [comment]
1.19.2? or 1.20

**Comment by screret** [comment]
PR targets 1.19.2, should be cherrypicked to both

**Comment by Yefancy** [comment]
I can check the cutter recipes in 1.19.2 fabric. so I thought it was a bug of 1.20

**Comment by screret** [comment]
it was the CraftingComponent for tiered glass in machine recipes that had the correct tag

**Review by Yefancy — APPROVED** [review]

**Pull request merged**
