### PR TITLE
fix: compile errors

### PR DESCRIPTION
**Pull request by mikerooni**
## What
Fixes recent compile errors

### CODE REVIEW

**Review by TheAlaskanPhysicist — APPROVED** [review]
Thank you Mike

**Review by TheAlaskanPhysicist — CHANGES_REQUESTED** [review]
Not yet bozo :P

**Comment by mikerooni** [comment]
Alright, now I'm done (this time for real) :lets:

**Review by TheAlaskanPhysicist — APPROVED** [review]
Absolute lifesaver, you are

**Pull request merged**
