### PR TITLE
Uncreate Create Compat.

### PR DESCRIPTION
**Pull request by Ghostipedia**
## What
Removes All Create Compat, RecipeCaps and all things related to Create from GTCEU:Modern

## Implementation Details

Right Click, Delete File
Highlight Line, Delete File

## Outcome

No More Create :)

## Potential Compatibility Issues
All Devs relying on KubeJS or Mod Compat with the Create Mixins and Functionality inside of GTCEU:MODERN Will need to do one of the following

- Take the Old Code Removed in this PR and make their own addon. You are now entirely responsible for making your Create Compat good and stable as the initial implementation inside of GTM should have never existed to begin with and was riddled with longstanding bugs and compat issues.

## Additional Information
i was at house, eating chicken... when phone ring...
"Create compatibility is kil"
"Yes..."
366323089-506e888e-af82-43a2-a262-bce5e9495400

### CODE REVIEW

**Comment by screret** [comment]
> Highlight Line, Delete **File**

buddy

**Comment by Ghostipedia** [comment]
Still working on this, spotless will fail, double checking i got everything

**Comment by Spicierspace153** [comment]
discord ping
>modern dev talks
>create is kill
>approved

**Comment by za23aet** [comment]
i was at house, eating ice cream... when discord ping...
"Create compatibility is kil"
"Yes..."

**Comment by JuiceyBeans** [comment]
i was at house, eating ice cream... when discord ping...
"Create compatibility is kil"
"Yes..."

**Review by screret — APPROVED** [review]
don't see anything errant at least

**Comment by Ghostipedia** [comment]
If we find anything outstanding in the future or unused method in the main code. Ig just doublecheck if it was related to this and append it here for any future addon devs that may need it. Going to merge this now.

**Pull request merged**
