### PR TITLE
cherrypick 1.2.0 to 1.19

### PR DESCRIPTION
**Pull request by screret**
because someone else didn't do it and I want the update out already.

### CODE REVIEW

**Comment by Arborsm** [comment]
+162,618 −68,813 wtf

**Comment by screret** [comment]
tf you mean conflicts what happened

**Comment by screret** [comment]
OH I TARGETED 1.20

**Comment by screret** [comment]
there we go.

**Review by mikerooni — APPROVED** [review]
Too long didn't read :trollface:

Any significant changes I need to review for 1.19, or is it an exact cherrypick?

**Review by mikerooni — APPROVED** [review]

**Pull request merged**
