### PR TITLE
Fix Coke Oven Hatch gaps

### PR DESCRIPTION
**Pull request by kdcjxbsdnbgfdg**
## What
it should be accepted so there isnt gaps between blocks bc the model is wrong

## Implementation Details
i just changed some values, it doesnt even cause any z fighting or anything theres no issue

## Outcome
i chaged some values so theres no gaps between blocks

## Additional Information
image
image
no longer any gaps

### CODE REVIEW

**Review by screret — COMMENTED** [review]
does it not z-fight now?
also,
> Please fill in as much useful information as possible. Also, please remove all unused sections, including this and the other explanations.

**Comment by jtuc** [comment]
Tested on Intel Iris Xe Graphics; can confirm no Z-fighting or seams with both Vanilla and Embeddium rendering.
image
For comparison, GregTech 1.5.4 (seams visible):

**Comment by MatthiasMann** [comment]
doesn't this now render 2 faces on the north face?

**Comment by screret** [comment]
that's what it's always done

**Review by screret — APPROVED** [review]

**Comment by MatthiasMann** [comment]
can't we just remove the north face from texture 1?

**Pull request merged**
