### PR TITLE
fix(EURecipeCapability): fix getMaxParallelRatio method

### PR DESCRIPTION
**Pull request by DancingSnow0517**
## What
when is WorkableElectricMultiblockMachine, error use getOverclockVoltage to calc MaxParallel

### CODE REVIEW

**Review by screret — CHANGES_REQUESTED** [review]
this hardcodes it to 1A of the machine voltage. that shouldn't be the case.

**Comment by DancingSnow0517** [comment]
in [this](https://github.com/GregTechCEu/GregTech-Modern/blob/4beed389957fc25cb2873e703f88ef8280306d1b/src/main/java/com/gregtechceu/gtceu/common/data/GTRecipeModifiers.java#L62) line code, will check machine voltage 1A with modified recipe EUt, that when machine voltage same with recipe voltage , Parallel larger then 1, the machine will not working

**Comment by DancingSnow0517** [comment]
so i let getMaxParallelRatio use 1A of the machine voltage to calc MaxParallelRatio.

**Comment by screret** [comment]
> in [this](https://github.com/GregTechCEu/GregTech-Modern/blob/4beed389957fc25cb2873e703f88ef8280306d1b/src/main/java/com/gregtechceu/gtceu/common/data/GTRecipeModifiers.java#L62) line code, will check machine voltage 1A with modified recipe EUt, that when machine voltage same with recipe voltage , Parallel larger then 1, the machine will not working

that's the overclock...

**Comment by DancingSnow0517** [comment]
I modifed code also aligns with GCYM's performance, machine voltage same with recipe voltage, will only heve one Parallel.

**Comment by DancingSnow0517** [comment]
> > in [this](https://github.com/GregTechCEu/GregTech-Modern/blob/4beed389957fc25cb2873e703f88ef8280306d1b/src/main/java/com/gregtechceu/gtceu/common/data/GTRecipeModifiers.java#L62) line code, will check machine voltage 1A with modified recipe EUt, that when machine voltage same with recipe voltage , Parallel larger then 1, the machine will not working
> 
> 这就是超频......

but why machine will not working? use modifed recipe EUt to calc recipe voltage, let machine voltage less than, This is not as expected

**Comment by DancingSnow0517** [comment]
or apply Parallel before overclock

**Comment by screret** [comment]
please try building #1365.

**Comment by DancingSnow0517** [comment]
> please try building #1365.

sure, when action build finished, i will test it.

**Comment by DancingSnow0517** [comment]
> please try building #1365.

it work fine.

**Pull request closed without merging**
