### PR TITLE
cherrypick the alloy blast fix to 1.20

### PR DESCRIPTION
**Pull request by Rundas01**
seems to have worked :3

### CODE REVIEW

**Comment by screret** [comment]
No need, i have the full cherrypick ready already lol

**Comment by screret** [comment]
It's just waiting on ME hatches to be merged

**Comment by Rundas01** [comment]
aight, what about oreproc page?

**Comment by screret** [comment]
Also in there
I just accidentally amended commit

**Comment by Rundas01** [comment]
aight

**Pull request closed without merging**
