### PR TITLE
Fix ore vein changes being overwritten.

### PR DESCRIPTION
**Pull request by Fuyukai**
See #1435.

### CODE REVIEW

**Comment by screret** [comment]
Did you test that this change doesn't actually leave any ore veins dangling around?

**Comment by screret** [comment]
Also you need to run spotless

**Comment by Fuyukai** [comment]
I tested it with the integrated server this morning and then the dedicated server (fixes the bug, and doesn't leave ore veins hanging) but re-tested it with the dedicated server *first* when I woke up and found a classloading bug that I didn't notice the first time, fixed in the subsequent commit. (There's no possible code path where old veins are left hanging anyway.)

Ore veins are still semi-broken in the REI display, but that happens on the trunk anyway and I believe is down to an REI misbehaviour of it just not reloading plugins after a reconnect.

**Review by screret — APPROVED** [review]

**Comment by AncientShotgun** [comment]
Sorry to necro this, but should I make a note of this issue in the packdev section of the docs for the versions affected by it?

**Pull request merged**
