### PR TITLE
Allow using materials with ingots or gems for beacons

### PR DESCRIPTION
**Pull request by mikerooni**
Blocks can be used for the beacon base. Ingots and gems can be used for beacon payment.

### CODE REVIEW

**Comment by mikerooni** [comment]
Do we actually want to have all listed gems as beacon payment items?

Things like salt should probably not be included imo.

**Comment by Hexasphere0** [comment]
Probably only use rare gems, for ingots maybe use all alloys or non-basic materials like aluminium.

**Comment by screret** [comment]
I think it should be a material flag, and injected in `TagLoaderMixin` like the other material block/item tags.

**Comment by mikerooni** [comment]
Hmm, not sure how I'd go about it yet, but I think I'll close this PR in favor of a new implementation using `TagLoaderMixin`, while I continue working on covers.

**Pull request closed without merging**
