### PR TITLE
fix air requirement in rotary hearth furnace

### PR DESCRIPTION
**Pull request by sreny1**

### CODE REVIEW

**Review by mikerooni — APPROVED** [review]

**Comment by screret** [comment]
I fixed this in #412, it just needs to be cherrypicked.
That PR also had some other fixes for the multiblocks' shapes

**Comment by sreny1** [comment]
@screret what you did in #412 was adding 'A' for air in the hearth furnace, but you left '#' to also be air.
another thing overlooked was defining 'M' for Muffler hatch twice.
In the current version i was unable to build a valid rotary hearth furnace (even placed by terminal in creative) and i was hoping this would fix it

**Comment by screret** [comment]
well did it fix it?

**Comment by sreny1** [comment]
i don't know how to test it, but i was hoping its the double muffler hatches

**Pull request merged**
