### PR TITLE
Fix shutter cover exposing item and fluid handlers

### LINKED ISSUE #2542: Shutter over next to AE2's Molecular assembler doesn't block input.
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.20.1-1.5.5-SNAPSHOT-20241210

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Monifactory

### Expected Behavior

When a machine is next to a standalone AE2 molecular assembler, with a shutter cover on the side adjacent to the molecular assembler, the assembler should not be able to push into the machine.

### Actual Behavior

The molecular assembler will push into the machine through the side with a shutter cover.

### Steps to Reproduce

1. Place a machine next to a molecular assembler.
2. Provide AE2 power to the molecular assembler (e.g. a creative energy cell).
3. Put a shutter cover in the machine on the side of the molecular assembler.
4. Put a pattern into the machine (i.e. sand -> sandstone).
5. Put the ingredients into the assembler.
6. Observer that the output is pushed into the machine.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by omergunr100**
## What
When a machine has a shutter cover the side shouldn't expose an item/fluid handler.

## Implementation Details
Override the get capabilities methods on the shutter cover.

## Outcome
Fixes #2542

### CODE REVIEW

**Comment by screret** [comment]
does toggling the cover still work?

**Comment by omergunr100** [comment]
Honestly I didn't even know this cover was toggleable, I thought you place it where you don't want the machine to expose the handlers.
I'll fix that.

**Comment by omergunr100** [comment]
image
found another issue while testing it :trollface:

**Review by screret — APPROVED** [review]

**Review by krossgg — APPROVED** [review]

**Comment by tomprince** [comment]
I can confirm that I can use a shutter in the location which prompted the issue. :tada:

**Pull request merged**
