### PR TITLE
Ender Link System

### PR DESCRIPTION
**Pull request by mikerooni**
The new Ender Link system, expanded with some new features (controllers, item transfer capability, multiple tiers, etc.).

### ToDo List:
- [x] Add ender fluid link cover, controller multiblock (with tiers) and linking card
- [ ] Add ender item link cover
- [ ] Add editable UI to the covers and controller / rework prototype UI
- [x] Implement connecting covers to controller (also match controller UUID, stored on linking card)
- [x] Implement virtual item & fluid transfer (proxy the storage of all covers on that channel)
- [ ] Implement linking multiple controllers (ensure that 2 channels are available per new controller in the network)
- [ ] Add multiple tiers for the covers
- [ ] Implement computing integration when 2.7 is merged
- [ ] Implement cross dimension networks
- [ ] Recipes and balancing
- [ ] Documentation

### CODE REVIEW

**Comment by mikerooni** [comment]
More TODOs as of the last push:

- [x] Add linking cards to drops on both covers and controller
- [x] Fix cards not being loaded initially (currently needs reinserting the card to be loaded, probably because of `@Persisted` handling)
- [x] Check if it's possible to make `TransferType` a registry instead of an enum
- [x] Consider transfer rate limit (requires moving the transfer logic to the controller and/or rate limiting the cover's returned transfer)
- [ ] Implement channel selection in cover UI
- [ ] Adapt channel count & range to tier
- [x] Implement range restrictions between controller and covers
- [x] Implement filtering
- [ ] Add remaining tiers for controllers

**Comment by mikerooni** [comment]
- [ ] Potential rework necessary for `ProxiedTransferWrapper` and transfer logic to better support IO type `BOTH`

**Possible implementation** - Transfer in two distinct steps:
1. Move everything from `IO.IN` to `IO.OUT` and then `IO.BOTH`
2. Move everything from `IO.BOTH` to `IO.OUT` only

**Review by TheAlaskanPhysicist — COMMENTED** [review]
LGTM currently, lmk if you want approval (lots of merging we'll have to do lolol)

**Comment by mikerooni** [comment]
I'm closing this one for now - in favor of starting over, if I work on it in the future ^^

### Additions to revisit and possibly add to the current codebase:
- [common/src/main/java/com/gregtechceu/gtceu/api/transfer/proxies/](https://github.com/GregTechCEu/GregTech-Modern/tree/cff36983e320b5703281437a9b742ea767d47374/common/src/main/java/com/gregtechceu/gtceu/api/transfer/proxies)
- [common/src/main/java/com/gregtechceu/gtceu/api/misc/FluidAmountHandler.java](https://github.com/GregTechCEu/GregTech-Modern/blob/cff36983e320b5703281437a9b742ea767d47374/common/src/main/java/com/gregtechceu/gtceu/api/misc/FluidAmountHandler.java)
- [common/src/main/java/com/gregtechceu/gtceu/api/misc/SideLocal.java](https://github.com/GregTechCEu/GregTech-Modern/blob/cff36983e320b5703281437a9b742ea767d47374/common/src/main/java/com/gregtechceu/gtceu/api/misc/SideLocal.java)

**Pull request closed without merging**
