### PR TITLE
remove generic from `IMaterialProperty`

### PR DESCRIPTION
**Pull request by a-a-GiTHuB-a-a**
For some reason, `IMaterialProperty` has a generic property. The only use seems to recursively store…itself? I dunno. `T` wasn't even used at all in the interface.

### CODE REVIEW

**Comment by Spicierspace153** [comment]
spotless apply 🗣️ 🗣️ 🗣️ 🗣️

**Comment by a-a-GiTHuB-a-a** [comment]
> spotless apply 🗣️ 🗣️ 🗣️ 🗣️

done

**Review by screret — APPROVED** [review]
we should move all the built in material properties to common/ at some point...

**Comment by a-a-GiTHuB-a-a** [comment]
someone should make a great big refactoring pr like they did in 1.21

**Review by YoungOnionMC — APPROVED** [review]

**Pull request merged**
