### PR TITLE
Fix description of Impure ore cauldron actions

### PR DESCRIPTION
**Pull request by Ghostipedia**
Fixes the description of "Throw into Cauldron to get clean Dust" to "Right click a Cauldron to get clean Dust" - to properly mirror its in game behavior.

Did this patch no only because people playing my pack got confused, but I'd assume people playing modern standalone would too

### CODE REVIEW

**Comment by Arborsm** [comment]
hm, no,  you should do it in the LangHandler or something

**Comment by Arborsm** [comment]
https://github.com/GregTechCEu/GregTech-Modern/blob/797ce31f5429cf329e213e72f6460e433877c0ad/src/main/java/com/gregtechceu/gtceu/data/lang/LangHandler.java#L118

**Comment by Arborsm** [comment]
and run data-gen

**Comment by Ghostipedia** [comment]
> https://github.com/GregTechCEu/GregTech-Modern/blob/797ce31f5429cf329e213e72f6460e433877c0ad/src/main/java/com/gregtechceu/gtceu/data/lang/LangHandler.java#L118

Oh I wasn't even aware this file existed, It still needs to be updated in en_us as well though imo otherwise it makes the langhandler change moot, no?

**Comment by Arborsm** [comment]
> Oh I wasn't even aware this file existed, It still needs to be updated in en_us as well though imo otherwise it makes the langhandler change moot, no?

run the data-gen task will auto generate the lang file (eu_us) by those lang things

**Review by TheAlaskanPhysicist — APPROVED** [review]
I like the clarity.

**Pull request merged**
